#!/bin/sh

# Modify values below
PROJECT_ROOT_DIRECTORY=/home/igor/IO
VISUAL_PARADIGM_DIRECTORY=/opt/visual_paradigm/Visual_Paradigm_17.1

# DO NOT CHANGE VALUES BELOW
PROJECT_FILE_PATH="${PROJECT_ROOT_DIRECTORY}/Konto_Bankowe.vpp"
DIAGRAM_IMAGE_DIRECTORY="${PROJECT_ROOT_DIRECTORY}/extras"
VISUAL_PARADIGM_EXPORT_SCRIPT="${VISUAL_PARADIGM_DIRECTORY}/bin/ExportDiagramImage.sh"